### ISSUE TITLE
Examine all copyright designations to ensure correctness

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/meta-bistro#1]
Want to ensure we're assigning copyright where we ought to.

**Comment by tobsan** [comment]
Also, make sure that we don't claim copyright for recipes that we originally pulled in from other layers.

**Comment by jeremiah** [comment]
Verbatim from a lawyer who works for a Major Multinational Corporation: "[All Rights Reserved] is surplus usage and obsolete;  a holdover from a centuries-old treaty long-since superseded:  http://en.wikipedia.org/wiki/All_rights_reserved
 
I think it now should be interpreted as essentially “no other rights are granted other than the rights granted in the appended license” (which most licenses say anyway).
 
The only remaining value (other than historical) of this statement is that it was rather deftly parodied by the FSF as “All Rights Reversed” "

I plan to remove the term where I find it, unless of course there are objections.

**Comment by jeremiah** [comment]
Ugh, search for 'copyright' in the meta-bistro repo; "We've found 104 code results" :-)

**Comment by jeremiah** [comment]
All the copyright designations for Pelagicore that I found were in .bb files or .bbappend files. This is metadata and as such I doubt is it copyrightable. I won't hurt anything, but its important to know that it won't do what one might think it will do; namely provide some sort of legal protection or provenance. In any case, the copyright designations are not incorrectly assigned and therefor nothing needs removing. Closing this issue.

**Comment by Gagi2k** [comment]
Mhh i would treat bb files and bbappends as build system code and not like metadata. I don't think we have that case, but a very complex bb file should be copyright worthy

**Comment by jeremiah** [comment]
Good to know, and you may in fact be correct that a complex bb file might be copyright worthy although I don't know if there has been much case law in the US or Germany for us to make a reasonable decision. Because of that, let's leave the copyright designations in place in case they *are* copyrightable.

**Comment by erikboto** [comment]
A complex bb-file probably include code (bash and/or python) so it should really be copyrightable. But I don't have any opinion on whether we should have copyright designations or not.

**Comment by jeremiah** [comment]
I should have recognized that it might include code, in which case you're right it ought to be copyrightable, and then under copyright assignment.
