### ISSUE TITLE
Split softwarecontainer to .bb and .inc

### ISSUE THREAD

**Issue by jonte** [Pelagicore/meta-bistro#109]
Create a .inc-file for softwarecontainer which contains all PACKAGECONFIG and other settings, and create a bb-file with the defaults we want in meta-bistro. This should make it easier for other layers to configure softwarecontainer as they see fit.

**Comment by jonte** [comment]
@GordanM Does this make sense?

**Comment by GordanM** [comment]
@jonte valid point!

**Comment by GordanM** [comment]
Hey Jonatan, I've reevaluated the point you made and had some second thoughts. To me it seems like the usual scenario is that the recipes have a default package configuration set in the original recipe via `PACKAGECONFIG ?(?)= ` and the users will adapt their own `PACKAGECONFIG` setup depending on their needs in a project specific layer bbappend file. 

Does that sound reasonable to you?

**Comment by jonte** [comment]
Hi @GordanM 

Yep, that does also sound like a reasonable approach to me, and we would achieve the same results.

**Comment by tobsan** [comment]
In my experience, .inc files are mostly used when there are several versions etc with more differences than simply PACKAGECONFIG or similar. In this case I don't see the benefit from it.

**Comment by GordanM** [comment]
Well put @tobsan. @jonte would you be OK with closing this issue?

**Comment by jonte** [comment]
Yep, works for me. Did we capture the PACKAGECONFIG modifications in a difference issue somewhere?

**Comment by tobsan** [comment]
So, right now we have a `PACKAGECONFIG ?= "some options here"`. We can of course add more PACKAGECONFIG entries to ease configuration, but apart from that I think we got things covered wrt what this issue describes.
