### ISSUE TITLE
tracker recipes are broken with Yocto 2.2

### ISSUE THREAD

**Issue by GordanM** [Pelagicore/meta-bistro#122]
There are several `Missing or unbuildable dependency chain` that might be broken even before 2.2 (morty). 

Are these recipes being used or should we rely on the mainstream recipe of tracker, instead of our fork (https://github.com/Pelagicore/tracker-ivi)? @jonte could you please comment on this?

**Comment by jonte** [comment]
@GordanM tracker-ivi is completely unmaintained, we should definitely rely on upstream tracker.

**Comment by GordanM** [comment]
@jonte thanks for the feedback!
