### ISSUE TITLE
Replace git:// with https:// in recipes

### ISSUE THREAD

**Issue by rpannek** [Pelagicore/meta-bistro#131]
Often inside of corporate networks the git port 9418 is blocked, to make it easier for meta-bistro to get adopted by others we should not use the git:// protocol but https:// instead if it is possible. When doing fetchall I saw that those two recipies use git:// and could just be replaced with https:// because they point to github.com which allows that.

./meta-bistro/layers/qt5-layer/recipes-qt/swaplogger/swaplogger.bb
./meta-bistro/recipes-core/systemd/systemd-additional-units.bb

But I think we should change all the ones we have in meta-bistro, because most of them point to ones which can handle https.

**Comment by Gagi2k** [comment]
The best would be to use a setting in local.conf to switch it, in my opinion the default should still be git as it should be faster

**Comment by GordanM** [comment]
@Gagi2k valid point, though that seems like a solution that would depend on which local.conf you are using. Currently the local.conf used by Pelux and other projects using meta-bistro do not rely on meta-bistro's local.conf. We had several experiences where the build server was not allowed to use the git protocol and it is quite cumbersome to manually edit the local.conf of those machines. Other sources said that it was probably for the best to move the protocol to git over http.

**Comment by Gagi2k** [comment]
mhh ok, how about adding a conf file for enabling the https urls and use this on the build server ?

https://stackoverflow.com/questions/17366984/is-it-possible-to-pass-in-command-line-variables-to-a-bitbake-build

**Comment by rpannek** [comment]
I guess it could be done, but is it worth the effort? How much time will we save every build? 0,2 miliseconds? To get the time back by using conf files and so on we would need to build trillions of builds which we never will. (Just my 2 cents)

**Comment by rpannek** [comment]
I just had a quick google search and there seems to be no penalty using http(s) anymore: https://stackoverflow.com/questions/3248779/which-is-faster-ssh-or-git-protocol#3248848
