### ISSUE TITLE
Maven class integration cleanup

### ISSUE THREAD

**Issue by frznlogic** [Pelagicore/meta-bistro#15]
We are currently missing proper integration of the maven classes, they should only be added for the ivi layer.

**Comment by socec** [comment]
The maven bbclass is not being used anywhere, although it has some nice features. Might be worth shaping up.
The maven-properties.bbclass is full of commented out code, should be revisited.

I would also like to revisit the question of whether these classes should really be added only for the ivi layer.

**Comment by tobsan** [comment]
An issue with classes is that they are not searched for the same way as recipes, so conditional inclusion of classes is harder to achieve than for recipes. The easiest way to make it work would be to have a layer inside the layer (like the BSP layers works now).

To me, maven seems more generic than only IVI-layer (assuming we're talking about meta-ivi here), so if we want to keep them at all (do we?) we should fix them up and have them always active, so to speak.
