### ISSUE TITLE
Review GitHub meta-bistro/wiki for suitability of our public wiki

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/meta-bistro#18]
https://github.com/Pelagicore/meta-bistro/wiki

**Comment by jeremiah** [comment]
The goal here is to set up a document base for meta-bistro to make it easier to install, use, and contribute to. If GitHub's wiki is good enough, let's use it, if we need other features, we can capture those needs here.

**Comment by frznlogic** [comment]
My kneejerk reaction is that I'm not sure I like to use the wiki for that, I'd prefer to keep the basic instructions in the README so it's version controlled with the rest of the layer, and you get the necessary information on the "front page" straight away. We could the wiki for the deeper details perhaps, but right now I don't think we have that much deep details to understand?

**Comment by jeremiah** [comment]
Okay. That makes sense. In which case we'd have an INSTALL file and a README file in the repo, right?

**Comment by frznlogic** [comment]
Yes ;)
