### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by gunnarx** [Pelagicore/meta-bistro#21]
The words "All Rights Reserved" are found in combination with the copyright line at the top of some recipe files.  This wording is uncommon to use in combination with an open-source license.  It might not be strictly wrong (IANAL) but for clarity I wonder if you could decide on a single way to describe the license of the files in this meta-layer.   For example decide and adjust the following:

1. Avoid "All rights reserved", for clarity.
2. Should the recipe files include a license-specification header or not?
3. Make sure that whatever license information you choose for each recipe file is consistent with the main LICENSE file in the root

This would facilitate adoption.  Thanks in advance!

**Comment by jeremiah** [comment]
From what I've learned from lawyers who work with software licensing, "All Rights Reserved" is at best inaccurate and at worst untrue, after all open source licenses state that some of the rights are not in fact reserved but distributed, i.e. modification, etc. 

So for issue 1. I think we can comply.

For issue 2. my feeling is that if there is a blanket policy requiring SPDX headers then the recipe files should be no exception. Since its a comment that shouldn't be an issue? If there is something confusing about it or if you feel its unnecessary then we can remove them.

Issue 3. should be a given, I'll take a closer look.

Thanks, I'll send a pull request to the maintainer with any changes, once they're accepted I'll close this.

**Comment by gunnarx** [comment]
2. I would be fine with the recipes having a short copyright & license information if you choose to have it.  I just meant that you decide what you want to do across the whole repo -- I did not want to suggest anything specific there.

Thanks for looking into this.

**Comment by jeremiah** [comment]
81 files have "All rights reserved" somewhere in them. I'm going to have to go through them all I'm afraid.

**Comment by jeremiah** [comment]
Apologies for the delay. I will review this and post a status update, this issue is not dead.

**Comment by gunnarx** [comment]
OK, so now many / most recipes have a (C) line remaining but the All rights reserved, removed, and the root has a LICENSE file.

If a single recipe is copied from this collection it will be disconnected from the LICENSE file in the root.  That's not uncommon and can happen in other projects too.  Usually the recommended practice is to put some kind of license indication in the file.  It might not mean it's not legal to use the code without it -- it just means that whoever reads the code when disconnected from the LICENSE file might be *uncertain* about the license.

Yocto layers seem to be almost universally MIT licensed, and in particular for those, there are often copies made without bringing copyright/license information along.  We could argue if "metadata" like this is copyrightable work, but my point is simply that as it stands now, a receiver of a single file from this collection might be uncertain about the rights to use it.

My preference is therefore that if there is a copyright line, then there should also be a license indication in the same place.

If I do the work, would you accept a patch where we add a SPDX identifier just below the (C) line?

**Comment by gunnarx** [comment]
Also adding that currently two recipes differ from the others by still including "All rights reserved".  Is there a difference in licensing intended for them or is it coincidental?

* [recipes-support/ivi-logging/ivi-logging.bb](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-support/ivi-logging/ivi-logging.bb)
* [recipes-containers/softwarecontainer/softwarecontainer.bb](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-containers/softwarecontainer/softwarecontainer.bb)

**Comment by GordanM** [comment]
@gunnarx we would more than welcome to accept the patch with SPDX IDs below the (C) line.

On the other hand, usually Yocto recipes don't contain licence headers but as you have mentioned it: a copyright line might require a copyright header as the developer using the recipe might be confused by the copyright. 

@jeremiah do you have any information why do the two recipes mentioned by @gunnarx differ from others by including the "All rights reserved" line? I believe it to be purely coincidental but I would like your feedback on this. Thanks!

**Comment by jeremiah** [comment]
@gunnarx With regard to softwarecontainer.bb and ivi-logging.bb we haven't gotten around to bringing them into our current compliance expectations, that will happen but if someone wants to go nuts with sed and do a sed -e 's/All rights reserved//g' then I think we'd be happy with that.

**Comment by jeremiah** [comment]
FWIW I have created some templates that I believe are sufficient from a legal perspective, feel free to use them if they fit: https://github.com/Pelagicore/OpenSourceTemplates/blob/master/Example_header_metadata.md

**Comment by gunnarx** [comment]
@jeremiah 

> sed -e 's/All rights reserved//g' then I think we'd be happy with that.

OK, although I asked not only about removing that but about adding a license line.  Does it mean you agree with @GordanM's answer :

> @gunnarx we would more than welcome to accept the patch with SPDX IDs below the (C) line.


>FWIW I have created some templates that I believe are sufficient from a legal perspective, feel free to use them if they fit

Yes, I'd be OK with that.  Shall we conclude this informal one is preferred over SPDX?  Please align within Pelagicore and let me know - thanks.

**Comment by jeremiah** [comment]
For clarification;

1. My template was wrong, it has been updated to the formally defined standard
2. Yes, I agree with @GordanM that the SPDX license identifier line ought to come below copyright.

Sorry for any confusion.
