### ISSUE TITLE
Are we still using libitzam?

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/meta-bistro#22]
In recipes-support there is a recipe for libitzam. This code is dual licensed -- simplified BSD for open source projects like ours and commercial license for closed source projects. If we want anyone to use meta-bistro, we need to make it clear that using libitzam commercially requires a commercial license from upstream. More here: http://coyotegulch.scottrobertladd.net/products/itzam/c/index.html

If we're not using itzam, perhaps we remove this in order to avoid any confusion for downstream?

**Comment by tobsan** [comment]
If I'm not mistaken, itzam is the default backend for persistence common object from GENIVI. However, according to the docs, it is no longer supported, and users are encouraged to use key/value store instead.

The recipe in recipes-extended/persistence-client-library/ DEPENDS on libitzam. However, a recipe for PCL, PCO and libitzam exists in meta-ivi nowadays (and maybe has for a while). Imho, it does not make sense to need libitzam without wanting PCO, and then you'd want meta-ivi anyway.

Perhaps @rpannek can remember if we had some super unique use case back in the days, but I don't think we did.

**Comment by jeena** [comment]
You're right, I think we added it there just before it was depricated in PCL but never really used it. And it was depricated because of the license problems if I'm not mistaken. So as far as I can see we can just remove it.

**Comment by rpannek** [comment]
You're right, I think we added it there just before it was depricated in PCL but never really used it. And it was depricated because of the license problems if I'm not mistaken. So as far as I can see we can just remove it.
