### ISSUE TITLE
Is libspotify dead?

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/meta-bistro#23]
https://jonaslundqvist.net/2015/05/06/do-not-use-libspotify/

If libspotify is no longer used, perhaps we remove it?

**Comment by tobsan** [comment]
From the same guy, one day after the original blog post: https://jonaslundqvist.net/2015/05/07/do-use-libspotify-later-this-year/. According to the developer page, new stuff will come along later this year: https://developer.spotify.com/technologies/libspotify/

**Comment by jeremiah** [comment]
Do we have the legal rights to distribute this code to commercial projects? From what I can see it says non-commercial use only and the developer terms and conditions say that no redistribution is allowed. 

Should we remove this lib from the public meta-bistro?

**Comment by tobsan** [comment]
If that is the case, then we should definitely remove it.

**Comment by frznlogic** [comment]
libspotify isn't really dead according to that link, but we opted to remove libspotify as it isn't used at this time as far as we can see. For any readers: If you object, notify us and we will re-add it.
