### ISSUE TITLE
Where do the build instructions live?

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/meta-bistro#29]
How does one build meta-bistro? Is qemu supported as a build target?

**Comment by jonte** [comment]
meta-bistro doesn't do much on its own. A common way to use it is together with the Poky Yocto distribution (as well as some other layers). The best way to get started it probably to start building Poky, read the docs concerning layers, and then add meta-bistro up your project. You'll find the docs here: https://www.yoctoproject.org/documentation

As a side-note, Pelagicore will release a Yocto guide which uses meta-bistro in some examples, but the official docs will suit you best for now.

**Comment by jonte** [comment]
Regarding qemu; it is not a supported target, but I do not forsee any obvious problems with using it. Let me know when you've tried it!

**Comment by rpannek** [comment]
Do we feel we can close this issue now, or should we update the README with some additional information?

**Comment by jonte** [comment]
ping @jeremiah. OK to close this?

**Comment by jeremiah** [comment]
Please close.
