### ISSUE TITLE
Status of openssh

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#53]
The [openssh recipe directory](https://github.com/Pelagicore/meta-bistro/tree/master/recipes-connectivity/openssh/openssh) offers systemd files for openssh but does not install them.
Similar files with extra configurable options and an install step is offered by Poky:
http://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/recipes-connectivity/openssh

Is there any reason to keep these files?
If yes, should a recipe for installing them be provided as well?

**Comment by erikboto** [comment]
I think this is legacy from before the openssh recipe provided systemd unit files that supported proper socket activation, we should just remove them now.
