### ISSUE TITLE
Neard bbappend

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#54]
The bbappend for [neard](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-connectivity/neard/neard_%25.bbappend) resets RRECOMMENDS due to a bluez version problem between Poky and meta-ivi. It is also marked with "FIX ME" referring to a pending change in Poky which seems to be merged.

Now the inherited bluetooth bbclass sets the BLUEZ variable to a value defined by DISTRO_FEATURES.

Should the bbappend be removed now?

**Comment by jonte** [comment]
+1 for removal.

**Comment by erikboto** [comment]
+1 for removal, legacy fixes not valid anymore.
