### ISSUE TITLE
Status of bluez4

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#56]
Bbappend for [bluez4](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-connectivity/bluez/bluez4_4.101.bbappend) directly creates symlinks for systemd service which should be handled through a systemd bbclass.

Also, bluez4 is considered obsolete in Poky since Jethro and is accessed from meta-oe:
http://www.yoctoproject.org/docs/2.0/ref-manual/ref-manual.html#migration-2.0-removed-recipes
Are the bbappend additions (audio profiles patch and MediaPoint dbus interface config) something we want to keep configuring by default when using meta-bistro?

**Comment by jonte** [comment]
No reason to use bluez4 that I can see. I've been using Bluez5 a lot, and everything works.

**Comment by erikboto** [comment]
I agree with @jonte, let's remove this.
