### ISSUE TITLE
Mutagen recipe is broken

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#60]
The recipe for [mutagen](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-devtools/python/mutagen_1.21.bb) is outdated, the links in HOMEPAGE and SRC_URI are dead.

Do we need this tool in meta-bistro?
If yes, should we write a new recipe that refers to https://pypi.python.org/pypi/mutagen ?

**Comment by jonte** [comment]
I think we can remove it. We can add it back again if anyone needs it.
