### ISSUE TITLE
Status of python-netaddr

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#61]
We have a recipe for [python-netaddr_0.7.10](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-devtools/python/python-netaddr_0.7.10.bb) but a newer version (0.7.18) is available in [meta-python](http://cgit.openembedded.org/cgit.cgi/meta-openembedded/tree/meta-python/recipes-devtools/python/python-netaddr_0.7.18.bb?h=master).

Do we want to keep this particular version of the recipe?

**Comment by DunderRoffe** [comment]
We have install all the latest packages using pip in vagrant-cookbook so I think it would be nice to update the recipes as well :)

**Comment by socec** [comment]
Since no component in meta-bistro depends on this particular version this recipe will be removed.
A project using meta-bistro should get it directly from the meta-python layer.
