### ISSUE TITLE
Polkit variable

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#64]
Bbappend for [polkit](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-extended/polkit/polkit_0.113.bbappend) sets a variable POLKITAUTH.

The explanation is that "default meta-oe value is consolekit" but I can't seem to find this variable in meta-oe. I would appreciate help in defining the need for this variable and how it is used.

NOTE: this recipe was *renamed* from polkit_0.111 to polkit_0.113, could be related to old version...

**Comment by rpannek** [comment]
@erikboto should know that but I suspect it's still in there from the time when poky didn't do systemd per default.
