### ISSUE TITLE
persistence-client-library

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#65]
Is there a point in maintaining [our own recipe](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-extended/persistence-client-library/persistence-client-library.bb)?

The official from meta-ivi should be used.

**Comment by tobsan** [comment]
I do believe there was some issues with the meta-ivi recipe, but that was a year or so ago. Perhaps @rpannek can remember it better than me?

**Comment by rpannek** [comment]
Yes, we needed it in a previous project we needed a newer version of it and the one in meta-ivi was really old and unmaintained. But we can remove it now.

**Comment by socec** [comment]
Thanks, it will be removed then :)
