### ISSUE TITLE
tracker_0.14.2: Recipe divergence from meta-oe

### ISSUE THREAD

**Issue by GordanM** [Pelagicore/meta-bistro#77]
The recipe in meta-openembedded/meta-gnome is somewhat different, mostly with updated dependencies. 

The question is should we keep a copy of this recipe in meta-bistro or remove it and state a dependency towards meta-openembedded/meta-gnome?

**Comment by rpannek** [comment]
If there is a activelly developed recipe in meta-oe then we should remove it from meta-bistro, we only had it in here because upstream had a too old version back then.
