### ISSUE TITLE
Using common-api code generator when rebuilding from sstate-cache

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#81]
While rebuilding from sstate-cache on Yocto 2.1. it was, rarely but still, observed that some components using the CommonAPI code generator were missing parts of the tooling supposed to be pulled in by this list of dependencies.

**Comment by sashko** [comment]
@thenor @GordanM anyone of you knows what was this about?

**Comment by thenor** [comment]
@sashko No sorry. Hoping @GordanM knows.

**Comment by GordanM** [comment]
Closing this issue as it was observed almost 2 years ago. Since then, capi generators, as well as the Yocto caching, changed. If we observe the issue again we will open a follow up.
