### ISSUE TITLE
XDG_RUNTIME_DIR should not be /tmp

### ISSUE THREAD

**Issue by socec** [Pelagicore/meta-bistro#88]
Setting XDG_RUNTIME_DIR to /tmp is invasive to the underlaying system because a chmod system call will be executed on /tmp to set 0700 permissions. Details about this can be found in the [qtbase code](https://github.com/qt/qtbase/blob/dev/src/corelib/io/qstandardpaths_unix.cpp#L154).

It should be something line with "/run/user/<id>", or even better, inherited from the system.

Therefore [this line](https://github.com/Pelagicore/meta-bistro/blob/master/recipes-core/softwarecontainer/files/softwarecontainer-agent.service#L10) should be reconsidered.

**Comment by jeena** [comment]
Some more info can be found here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by rpannek** [comment]
Some more info can be found here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by jonte** [comment]
I agree with @socec.

In general, this issue should be solved by having a policy of how to handle the D-Bus session bus in Bistro.

I think the most elegant solution would be to use systemd user sessions, and create a dbus session bus for each user session. I tried this once before, and it is nontrivial. I am not sure what a good intermediate solution would be.

**Comment by rpannek** [comment]
XDG_RUNTIME_DIR is not only used for D-Bus sessions, by the QtApplicationManager it is for example used for some wayland sockets if I'm not compleatly mistaken.

**Comment by jonte** [comment]
@rpannek You're completely right. And of course it should be in the same place for all applications.

I think it would make sense to invest some time in looking at systemd user sessions for setting this variable to the right value for all applications in the session.

**Comment by socec** [comment]
Ok, it seems we have an agreement that this should be handled on another level and make sure it is aligned.
I will revert the last commit that sets it for SC in meta-bistro. @kursatkobya  said he will make it part of a PR in meta-pelux.

**Comment by kursatkobya** [comment]
Yeah done it already. Maybe it would be sensible to move this now.

**Comment by GordanM** [comment]
Fixed with the following commit: https://github.com/Pelagicore/meta-pelux/commit/6703bcbe418fda6de1cd3d1ab556c1f2350135fe
